### ISSUE TITLE
Allow reading N bytes into a &mut [u8] at once

### ISSUE THREAD

**Issue by leoschwarz** [irauta/bitreader#10]
Hi, this crate seems to implement most of what I need right now, except there doesn't seem to be an easy way to read many bytes at once. 

I wanted to propose implementing a [read method](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) like here, however I'm not sure if you'd like the reader to implement `std::io::Read` or not. The benefit of implementing Read is that I could use it directly with other parts of my code where I sometimes also read from non BitReader Read implementors (but if there was any method I could also just implement Read using a new type).

I'm going to implement in my own fork first anyway, but I wanted to hear if there is any objection to such functionality to be added here?

**Comment by irauta** [comment]
I have nothing against having some kind of "read_slice_u8" method (or whatever would be the best name for it), or even implementing `std::io::Read` in principle, except for one worry.

The currently available methods operate pretty explicitly at the level of individual bits, whereas `Read` (or the hypothetical read_slice_u8) work on full bytes, so I'm a bit worried that there could be confusion on whether the read bytes are actually aligned with the bytes of the underlying slice or not. I mean, it seems kind of natural to impicitly assume that `Read` works with the "actual" bytes.

On the other hand, the user already has plenty of responsibility in knowing where the cursor is at any point and understanding the format that is being read, so I should probably just put my worries aside.

**Comment by leoschwarz** [comment]
This kind of worry is exactly why I asked instead of just sending a PR. Personally I'd prefer if reading the byte slice would just follow the bit cursor, i.e. reading byte by byte by performing an equivalent of a `read_u8`, but less expensive than calling the method N times. It could have some optimization for when the data is aligned properly, and should do something relatively efficient for when it is not.

Maybe for this reason it makes more sense to implement a method and not the trait, if someone wants to use it as Read they can just wrap it in another struct and implement Read on that?

**Comment by irauta** [comment]
Yeah, maybe it's safer to start with a slice-reading method. A `Read` implementation should be easy enough to build on top of the existing functionality. (Though I imagine adding a remaining() method as a counterpart to the current position() method would help with that.)

**Comment by irauta** [comment]
I just added a `read_u8_slice` method that fills the given slice with data from the source slice. It's different from the `read` of `Read` in that it doesn't fill the slice partially if there's not enough data left. I felt that the explicitness is better here, considering BitReader doesn't do any sort of "streaming" from a `Read` source or similar itself. A `Read` wrapper can use the `remaining` method (that I also just added) to figure out a good length for a slice to read without causing an error. The implementation is currently pretty naive, but then again, there's opportunities for optimization in the code elsewhere too.

I haven't uploaded a new version to crates.io yet.

**Comment by leoschwarz** [comment]
Thanks. :) I think the method implementing a "stricter" version of the trait method is not a problem, because as you said the `remaining` method can be used in a wrapper to implement the Read trait like I initially proposed easily.

PS: From my side there's no rush uploading to crates.io, right now I'm fine using the crate directly from this repo.

**Comment by irauta** [comment]
I updated the doc comment on read_u8_slice to make it maybe a little more readable after reading your suggestions.

I'll close this issue now, but if there's still something, it can of course be reopened.
