### ISSUE TITLE
Implement ReadInto for bool?

### ISSUE THREAD

**Issue by rillian** [irauta/bitreader#3]
In https://github.com/mozilla/mp4parse-rust/pull/55 we do a lot of
```rust
let v: u8 = ReadInto::read(reader, 1);
if v > 0 {
    true_thing();
} else
    false_thing();
}
```

I think this could be improved if there was an `impl ReadInto for bool` so one could:
```rust
if ReadInto::read(reader, 1) {
  true_thing();
};
```

**Comment by rillian** [comment]
One question is what to do with multibit values. Do we `as bool` or return an `Err`?

**Comment by irauta** [comment]
Sure, reading individual bits into bools makes sense! Regarding reading multiple bits: looking at your PR, I agree, the traditional 0 => false, anything else => true sounds good. My gut says reading multiple bits to make a bool sounds unlikely to be intentionally happening in practice, but better not turn it into an error. The user has to be careful when reading any number of bits into any type in any case.

**Comment by irauta** [comment]
PR merged, I'll release 0.2.0 to crates.io next, just a moment.

**Comment by rillian** [comment]
Thanks! What do you think about implementing a `read_bool()` as well? We're mostly using `ReadInto` but it might be useful to others and would simplify the trait implementation.

**Comment by rillian** [comment]
Well, maybe it wouldn't simplify the ReadInto implementation. I was thinking it would allow reusing the macro for bool, but I'd prefer read_bool() take no argument and always read one bit, which means special-casing the trait implementation even if it's wrapping read_bool().

**Comment by irauta** [comment]
(I'll delay publishing 0.2.0 a bit, would be nice to publish both bool methods in one go.)

Hm, having a read_bool() in BitReader sounds sensible too. Not being able to use the macro for bools is not a problem, but yeah, the trait impl wouldn't be able to reuse a read_bool() that doesn't take a bit count. Having two essentially identical implementations of a method feels a little annoying, but it's not like other types that are like bool in this respect are about to appear, meaning it wouldn't be a terrible precedent.

The only potential "upcoming" types I see are the really wide integers (u128/i128, should fit without much trouble into the current code) and just maybe some helpers to read floating point values, whose reading methods likely would not take a bit count argument. If float support were to be added - I'm hesitant to consider it now, don't have enough knowledge/confidence to work with them on a low level - there could be a new helper trait, always reading the "native" amount of bits for the type.

All in all, adding a read_bool() would add four mostly duplicated lines of code to the new fn and also doesn't require fiddling with the lowest level reading code, so the cost for it doesn't sound too high at all.

**Comment by rillian** [comment]
Ok, I'll prepare a PR.

Good point about the number of bits not making sense for floating-point types either. It's too bad we can't just define no-argument variants of the read_*() methods.

I wouldn't worry about other types until someone asks for them. Big-endian values is another thing which may come up. A lot of network protocols are big-endian, but so far everything I've needed to read has been byte-aligned, so it's not been an issue.

**Comment by irauta** [comment]
...and 0.2.0 is now available at crates.io.
