### ISSUE TITLE
Consider dual-licensing the crate under MIT & Apache-2.0

### ISSUE THREAD

**Issue by nox** [irauta/bitreader#8]
Cc @irauta @rillian @antoyo 

This is now depended upon by mp4parse's, which is used in Servo. We would like to avoid non-dual-licensed dependencies in Servo, so it would be great if you would consider dual-licensing it.

Thanks in advance.

**Comment by irauta** [comment]
I'm willing to dual-license the crate under MIT and Apache-2.0 licenses, if @antoyo and @rillian as people who have contributed to it agree with this change.

**Comment by antoyo** [comment]
I agree.

**Comment by rillian** [comment]
I agree, on behalf of the Mozilla Foundation to re-license my contributions to bitreader under dual MIT and Apache-2.0 licenses.

**Comment by irauta** [comment]
The crate is now dual-licensed under the discussed licenses. The dual-licensed version is published as version 0.3.0 at crates.io, no other changes come with the new version.

**Comment by nox** [comment]
This should have been a non-breaking bump but ok.

**Comment by rillian** [comment]
Is the license part of the API? Ah, philosophy! :)
